[tool.ruff-sync]
# The source to sync from (supports GitHub/GitLab web URLs, raw file URLs, and git:// or git+https:// URLs)
upstream = "https://github.com/Kilo59/ruff-sync"
# `path` is only needed if the config file is NOT in the root directory of the upstream repo
path = "configs/fastapi"
exclude = ["lint.per-file-ignores"] # Keys to preserve in your local config
