name: ci

on:
  pull_request:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  static-analysis:
    strategy:
      matrix:
        task: ["lint", "fmt", "type-check"]
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install 3.10

      - name: Install dependencies
        run: uv sync --group dev --frozen

      - run: uv run invoke ${{ matrix.task }} --check

  tests:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --group dev --frozen

      - name: Run tests
        run: uv run coverage run -m pytest -vv

      - name: Generate coverage report
        run: uv run coverage xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Kilo59/ruff-sync
